# Generated by Django 5.0.4 on 2024-04-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('loc', models.IntegerField()),
            ],
            options={
                'ordering': ['loc'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyutping', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('loc', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsandsentences.topic')),
            ],
            options={
                'ordering': ['loc'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyutping', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('loc', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsandsentences.topic')),
            ],
            options={
                'ordering': ['loc'],
                'abstract': False,
            },
        ),
    ]
