# Generated by Django 5.0.4 on 2024-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsandsentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
