# Generated by Django 5.0.4 on 2024-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsandsentences', '0003_alter_topic_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='response_to',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl to select multiple.', related_name='responses', to='wordsandsentences.sentence'),
        ),
    ]
