# Generated by Django 5.0.4 on 2024-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsandsentences', '0004_sentence_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='cantonese',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='cantonese',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
